// AUTOGENERATED FILE: DO NOT EDIT
export const data = `id,name,image_file,is_token?,backside_file,mana_cost,type_line,mechanics_text,flavor_text,power,toughness,backside_name,backside_typeline,backside_mana_cost,backside_color,backside_mechanics_text,backside_flavor_text,backside_power,backside_toughness,illustrator,backside_illustrator,illustrator_portfolio,backside_illustrator_portfolio,errata_acknowledgements
1,Ambiville Ironstoad,Ambiville Ironstoad.png,,Ambiville Mystra's Kin.png,{1}{W},Legendary Creature — Human Bard,"{3}{W},{T},Put a verse counter on Ambiville Ironstoad: Search your library for an enchantment card with mana value equal to the number of verse counters on Ambiville Ironstoad, put it onto the battlefield, then shuffle your library.
Remove a verse counter from Ambiville Ironstoad: Ambiville Ironstoad phases out.",,1,2," Ambiville, Mystra's Kin",Legendary Creature — Human Wizard,{1}{U}{U},,"Flash
Whenever you cast an instant, you may cast a random sorcery from your hand as though it had flash. If you do, Ambiville, Mystra’s Kin gains your choice of hexproof or indestructible until end of turn. (You must still pay all associated costs for casting the spell this way.)",,2,1,Karl Witkowski,xlxbetoxlx,https://www.mutualart.com/Artist/Karl-Witkowski/7E197AE91A9540DF/Artworks,https://www.deviantart.com/xlxbetoxlx,"Karl Witkowski's name is spelled as ""Karl Witowski"" on the card. I regret the error."
2,Glimpse Ragnarök,Glimpse Ragnarök.png,,,{2}{W}{W},Sorcery,"Search target opponent’s library for a card with mana value of 7 or higher. Exile that card. For as long as that card remains exiled, its owner may cast it. A spell cast this way costs {3} more to cast.
Foretell 1W",,,,,,,,,,,,Emil Gustafsson,,https://slappiz.artstation.com/,,
3,Healing Verse,Healing Verse.png,,,{2}{W},Instant,"Gain 1 + X life, where X is the number of creatures you own in exile.
Draw a card.","Rune prefers to stay out of combat, supporting the Bindareien with his soothing stories.",,,,,,,,,,,Ralph Horsley,,http://www.ralphhorsley.co.uk/,,
4,Hug the Yeti,Hug the Yeti.png,,,{W},Sorcery,Target creature you control fights target creature you don’t control with greater power. Gain 3 life.,“Perhaps the yeti is simply misunderstood.” — Ambiville Ironstoad,,,,,,,,,,,Richard Corben,,https://corbenstudios.com/,,
5,Jarl's Guardsman,Jarls Guardsman.png,,,{2}{W},Creature — Human Soldier,"Vigilance
Whenever Jarl’s Guardsman enters the battlefield or attacks, goad target creature.",The Jarl chooses only the most veteran warriors of many battles to protect the keep.,2,3,,,,,,,,,Joan Francesc Oliveras,,https://jfoliveras.artstation.com/,,
6,Judge the Meek,Judge the Meek.png,,,{W},Enchantment — Aura,"Enchant creature
While enchanted creature has 1 or less power or toughness, it can’t attack or block, and its activated abilities can’t be activated.","The council judged a boy, ignorant in his youth.",,,,,,,,,,,Konstantinos Skenteridis,,https://kingkostasart.artstation.com/,,
7,No Pets Allowed,No Pets Allowed.png,,,{3}{W},Enchantment,"When No Pets Allowed enters the battlefield, exile all Beasts, Cats, Dogs, Dragons, Insects, and Wolves. Beast, Cat, Dog, Dragon, Insect, and Wolf creature spells cannot be cast.
When No Pets Allowed leaves the battlefield, return all cards exiled by it back under their owner’s control. ",We apologize for any inconvenience this may cause.,,,,,,,,,,,Lac-tic,,https://www.deviantart.com/lac-tic,,
8,Priest of the Æsir,Priest of the Æsir.png,,,{2}{W},Creature — Human Cleric,"Whenever a creature enters the battlefield under your control, gain 2 life. Then if it entered from a zone other than your hand, gain 1 life.","The robed man looked down at Will. “I will show you how to temper your spirit in service to the All-father, red one.”",2,4,,,,,,,,,Reza Afshar,,https://rezaafshar.artstation.com/,,
9,Seamstress Karl,Seamstress Karl.png,,,{W},Creature — Human Peasant,"Lifelink
Journey {W}{W}{W} — monocolored white nonland permanent",,1,1,,,,,,,,,Françoise Duparc,,https://www.mutualart.com/Artist/Francoise-Duparc/1D8AE40828A525F5/Artworks,,
10,Tale of Heroics,Tale of Heroics.png,,,{1}{W},Instant,"Target creature gains indestructible until end of turn. The next time that creature takes damage this turn, gain life equal to the damage dealt.",Kaldr and Ambiville spoke at length about their recent adventures as the humble town elder marveled in awe. “Wow!”,,,,,,,,,,,Concept4,,https://concept_4.artstation.com/,,
11,Blue Bard's Insight,Blue Bards Insight.png,,,{2}{U},Instant,"If you control a Giant, this spell costs {2} less.
You may counter target artifact or enchantment spell. If Blue Bard’s Insight was cast without paying its mana cost, scry 3.","“An axe, eh? Let me take a look.”",,,,,,,,,,,Wesley Tippetts,,https://westippetts.artstation.com/,,
12,Judge the Impotent,Judge the Impotent.png,,,{1}{U},Enchantment — Aura,"Enchant creature
While enchanted creature has toughness exceeding its power, it can’t attack or block, and its activated abilities can’t be activated.","The council judged a legend, paralyzed during his inaction.",,,,,,,,,,,Kleyos,,https://www.deviantart.com/kleyos,,
13,Relinquish Control,Relinquish Control.png,,,{U},Instant,"Return target creature to its owner’s hand. Until end of turn, that spell costs 1 less to cast.",Bjorn stifled tears as he watched Yrsa depart with his beloved pet.,,,,,,,,,,,Stella,,https://in.pinterest.com/stellabratcher/_created,,
14,Rune of Algiz,Rune of Algiz.png,,,{1}{U},Enchantment — Aura Rune,"Enchant permanent
When Rune of Algiz enters the battlefield, draw a card.
As long as enchanted permanent is a creature, it can’t be blocked.
As long as enchanted permanent is an Equipment, it has “Equipped creature cannot be blocked.” ",,,,,,,,,,,,Bjorgvin Gudmundsson,,https://www.bjorgvingudmundsson.com/,,
15,"Rune, the Blue Bard",Rune the Blue Bard.png,,,{2}{U},Legendary Creature — Giant Bard,"If Rune, the Blue Bard enters the battlefield from exile, its base power and toughness becomes 7/8.
{5}{U}{U}, {T}: Exile Rune, the Blue Bard, then return it to the battlefield under your control.
Journey {5}{U}{U} — Blue instant",A gentle storyteller with a giant secret.,2,3,,,,,,,,,Katarzyna Bekus,,https://www.instagram.com/littleulvar/,,
16,Seal of the Old Tyrant,Seal of the Old Tyrant.png,,,{2}{U},Creature — Wall,"Defender
When an opponent declares you as the target of an attack, choose one that hasn’t been chosen — 
• Create a 1/1 blue Spirit creature token with flying.
• Create a 2/2 blue Spirit creature token.
• Sacrifice this creature, then search your library for a blue creature with mana value 4 or higher, put it into your hand, then shuffle.",,0,4,,,,,,,,,Jonathan Dufresne,,https://jonathandufresne.com/,,
17,Thoughtful Karl,Thoughtful Karl.png,,,{U},Creature — Human Peasant,"Ward {3}
Journey {U}{U}{U} — monocolored blue nonland permanent",,1,1,,,,,,,,,Yuliya Litvinova,,https://litvinova.artstation.com/,,
18,Trouble in the Black Market,Trouble in the Black Market.png,,,{4}{U},Instant,"Exile a creature you control, then return it to the battlefield. Repeat this process 2 more times. Create a 1/1 black Human Rogue for each creature with a different name exiled this way.",Ambiville was trapped between two perils: wandering the ethereal plane and the thugs of the Jardhus underground.,,,,,,,,,,,DiegoGisbertLlorens,,https://www.deviantart.com/diegogisbertllorens,,
19,Vrækæ's Desolation,Vrækæs Desolation.png,,,{2}{U},Instant,"As an additional cost to cast this spell, tap a creature you control. That creature does not untap during its controller’s next untap step. You may ignore this cost if this spell was cast without paying its mana cost.
You may counter target spell. Draw a card.",The Bindareien were too late this time.,,,,,,,,,,,Andrei Pervukhin,,https://www.deviantart.com/andrei-pervukhin,,
20,Chainer of Draugr,Chainer of Draugr.png,,,{B},Creature — Human Shaman,"When Chainer of Draugr leaves the battlefield, sacrifice any creatures that were cast as a result of its Journey ability.
Journey {1}{B} — Zombie",,1,1,,,,,,,,,Unknown,,,,
21,Commune After Sacrifice,Commune After Sacrifice.png,,,{1}{B},Sorcery,"Choose one — 
• Scry 1, then draw a card. You lose 1 life.
• Shuffle target card in a graveyard back into its owner’s library.","As Will prayed, he felt the presence of great strength trying to reach him. “For power, comes sacrifice...”",,,,,,,,,,,Solfour,,https://www.deviantart.com/solfour,,
22,Draugr Berserker,Draugr Berserker.png,,,{3}{B},Creature — Zombie Berserker,"Menace
Sacrifice a creature: Draugr Berserker deals 1 damage to each opponent.",A formidable corpse of a great warrior; the townsfolk stood no chance.,4,2,,,,,,,,,Saad Irfan,,https://saadirfan.artstation.com/,,
23,Draugr Captor,Draugr Captor.png,,,{2}{B},Creature — Zombie Soldier,"When Draugr Captor enters the battlefield, each opponent discards a card.
Journey {3}{B} — Human with toughness 3 or less",,2,3,,,,,,,,,Gerald Brom,,https://www.bromart.com/,,
24,Fearful Karl,Fearful Karl.png,,,{B},Creature — Human Soldier,"Deathtouch
Journey {B}{B}{B} — monocolored black nonland permanent",,1,1,,,,,,,,,Andrew Mar,,https://www.andrewkmar.com/,,
25,Incursion of Hardatr,Incursion of Hardatr.png,,,{4}{B},Enchantment,"At the beginning of your upkeep, create a 1/1 black Human Shaman creature token. Then if you control 13 or more creatures, sacrifice Incursion of Hardatr.
Whenever one or more nontoken creatures die, create a 2/2 black Zombie Berserker creature token.
",,,,,,,,,,,,Toby Fox,,https://www.tobyfoxart.com/,,
26,Kaldr Volundormr,Kaldr Volundormr.png,,,{3}{B},Legendary Creature — Dwarf Artificer,"Whenever Kaldr Volundormr or another creature you control enters the battlefield from exile, destroy target creature.
Equip costs you pay cost {1} less.
Journey {4}{B} — artifact
","“Equal work, equal pay. We are not equals.”",4,3,,,,,,,,,1221s,,https://1221sartblog-blog.tumblr.com,,
27,Malevolent Vandr,Malevolent Vandr.png,,,{2}{B},Creature — Human Warlock,"Whenever you cast a black spell, if it was not cast from your hand, you gain 1 life and each opponent loses 1 life.
Journey {3}{B} — black instant or sorcery",,2,2,,,,,,,,,Adam Frank,,https://adamfrankart.artstation.com/,,
28,Phase Spider,Phase Spider.png,,,{3}{B},Creature — Spider,"Reach
{1}, {T}: Phase Spider phases out.",,3,6,,,,,,,,,Unknown,,,,
29,"Storolf, Jarl of Jardhus",Storolf Jarl of Jardhus.png,,,{1}{B}{B},Legendary Creature — Human Rogue,"Storolf, Jarl of Jardhus can’t be blocked by creatures with greater power.
Whenever Storolf, Jarl of Jardhus deals combat damage to a player, you may cast any number of cards from your hand with a Journey cost into exile. The Journey cost for cards cast this way is {1}.",,2,2,,,,,,,,,Anastasia Kustova,,https://reddress.artstation.com/,,
30,Vandr's Heartstone,Vandrs Heartstone.png,,,{2}{B},Artifact — Equipment,"When this is equipped, destroy all enchantments you don’t control attached to equipped creature.
{2}: Equipped creature phases out. Activate this ability only as a sorcery.
Equip {3}",,,,,,,,,,,,Sean Yang,,https://seanyangart.artstation.com/,,
31,Yrsa's Manipulation,Yrsas Manipulation.png,,,{1}{B}{B},Sorcery,Exchange control of two creatures until end of turn. Untap those creatures. They gain haste until end of turn. Their controllers sacrifice those creatures during your next end step.,"“Why the hesitation, dear Bjorn? Afraid of a little skin?”",,,,,,,,,,,Astri-Lohne,,https://sjursen.artstation.com/,,
32,Cave Kobold,Cave Kobold.png,,,{R},Creature — Kobold,"Menace
Journey {3}{R} — Dragon","“I’ll pick my teeth with your bones.”  — Bjorn the Giant, before confronting a frost dragon",0,1,,,,,,,,,Chris Malidore,,https://cmalidore.artstation.com/,,
33,Frenzying Redcap,Frenzying Redcap.png,,,{2}{R},Creature — Goblin Berserker,"Whenever a creature enters the battlefield, Frenzying Redcap gets +1/+0 until end of turn.
{T}, Sacrifice Frenzying Redcap: Frenzying Redcap deals damage equal to its power to another target creature.",Not all goats are as they seem.,3,2,,,,,,,,,Jumpei,,https://www.deviantart.com/jumpei,,
34,Frostdweller Goblin,Frostdweller Goblin.png,,,{R},Creature — Goblin,"As long as it is not your turn, Frostdweller Goblin gets +0/+1.
Journey {3}{G} — green creature with mana value 4 or less",,1,1,,,,,,,,,Simone de Paolis,,https://sidepa.artstation.com/,,
35,God-King's Censure ,God-Kings Censure.png,,,{1}{R}{R}{R},Instant,"Target creature you control deals damage equal to its power to each other creature. Until the beginning of your next upkeep, God-King’s Censure deals that much damage to creatures who enter the battlefield from zones other than its controller’s hand.",A single word. A journey’s end.,,,,,,,,,,,Bob Eggleton,,http://www.bobeggleton.com/,,"Bob Eggleton's name is spelled as ""Bob Eggleto"" on the card. I regret the error."
36,Judge the Defiant,Judge the Defiant.png,,,{2}{R},Enchantment — Aura,"Enchant creature
While enchanted creature has power exceeding its toughness, it can’t attack or block, and its activated abilities can’t be activated.","The council judged an outsider, reckless in his decisions.",,,,,,,,,,,Silentfield,,https://silentfield.artstation.com/,,
37,Motivated Karl,Motivated Karl.png,,,{R},Creature — Human Warrior,"Haste
Journey {R}{R}{R} — monocolored red nonland permanent",,1,1,,,,,,,,,Krassimir Mercier,,https://krazymeer.artstation.com/,,
38,Ransack the Estates,Ransack the Estates.png,,,{3}{R},Sorcery,"Destroy target land. Its owner creates two Treasure tokens.
Draw a card.","“We should team up like this more often, Shel!” —Bjorn the Giant",,,,,,,,,,,Bethesda,,,,
39,Stone Worm,Stone Worm.png,,,{5}{R},Creature — Worm,"Trample
When Stone Worm deals combat damage to another player, you may pay 4. If you do, exile target land that opponent controls. Then put a +1/+1 counter on Stone Worm.
When Stone Worm leaves the battlefield, return all lands exiled by it to the battlefield under their owner’s control.",,6,6,,,,,,,,,Alexandra Roslik,,https://sunju.artstation.com/,,
40,"Thorvaela, Vandr Killer",Thorvaela Vandr Killer.png,,The Coven of Isstnar.png,{1}{R}{R},Legendary Creature — Human Warrior,"Trample
Whenever a Cleric, Shaman, Warlock, or Wizard creature enters the battlefield, you may have Thorvaela, Vandr Killer deal damage equal to its power to that creature. When that creature dies this turn, transform Thorvaela, Vandr Killer. ",,4,3,The Coven of Isstnar,Legendary Creature — Horror,,B,"Trample
Whenever a Cleric, Shaman, Warlock, or Wizard creature dies, put a number of +1/+1 counters equal to that creature’s power on The Coven of Isstnar.",,5,5,itaXita,Davesrightmind,https://www.deviantart.com/itaxita,https://www.deviantart.com/davesrightmind,
41,"Will, Defiant Convict",Will Defiant Convict.png,,,{3}{R},Legendary Creature — Tiefling Berserker,"At the beginning of your upkeep, if you have no cards in your hand, Will, Defiant Convict deals 3 damage to any target.
Journey {3}{B}{R} — red or black sorcery",“I alone determine what I will or will not do.”,4,3,,,,,,,,,Soong E Dol,,https://dolsoonge.artstation.com/,,
42,Apothecary Volva,Apothecary Volva.png,,,{1}{G},Creature — Human Shaman,Journey {2}{G} — green sorcery with mana value 4 or less,,2,2,,,,,,,,,lombrascura,,https://www.deviantart.com/lombrascura,,
43,Basilisk Wasp,Basilisk Wasp.png,,,{1}{G},Creature — Insect,"Deathtouch, Flying
{2}{G}, {T}: Destroy target artifact.","“See this rot in the ironwood? You see that in your house, you move out right away. Or die trying.” — Tabitha, Isstnar resident",1,1,,,,,,,,,Putra Kamajaya,,https://www.deviantart.com/sikama-78,,An old username for Putra Kamajaya was listed as the art credit on this card. I regret the error.
44,Bjorn the Giant,Bjorn the Giant.png,,,{3}{G}{G},Legendary Creature — Human Giant Berserker,"Haste, trample
If Bjorn the Giant entered the battlefield this turn from exile, return it to your hand at the beginning of the next end step.
Journey {1}{G}{G} — Creature with power 3 or less",“I swing the log. I’ll lead the way.”,6,3,,,,,,,,,Marc Simonetti,,https://art.marcsimonetti.com/,,
45,"Bones, Ice-hearted",Bones Ice-hearted.png,,,{2}{G},Legendary Creature — Wolf,"When Bones, Ice-hearted attacks with at least one other creature, Bones, Ice-hearted gets +1/+0 until end of turn.
{2}{U}: Tap target creature an opponent controls.",Ambiville looked at Bones for a response. Bones had but one: a lazy snort from his great nose.,3,3,,,,,,,,,Wizards of the Coast,,,,
46,Captive Innkeeper,Captive Innkeeper.png,,,{2}{G},Creature — Human Peasant,"When Captive Innkeeper enters the battlefield, if its mana cost was not paid, you gain 5 life.","The innkeeper, typically rowdy, sagged his shoulders in defeat as the draugr clasped bindings around his wrists.",2,3,,,,,,,,,Davood Diba,,https://diba64.artstation.com/,,
47,Hunt for Game,Hunt for Game.png,,,{3}{G},Instant,"Destroy target blocking creature you don’t control. Search your library for a land card, reveal it, put it into your hand, then shuffle.",A mutual understanding grew between Bjorn and Will as they took part in their nightly hunts.,,,,,,,,,,,Vadim Gorbatov,,http://vgorbatov.ru/en/,,
48,Savage Karl,Savage Karl.png,,,{G},Creature — Human Warrior,"Trample
Journey {G}{G}{G} — monocolored green nonland permanent",,1,1,,,,,,,,,Kate Voynova,,https://www.deviantart.com/katevoynova,,
49,"Shel, Pack's Blood",Shel Packs Blood.png,,Shel Moon Champion.png,{2}{G},Legendary Creature — Human Werewolf,"When Shel, Pack’s Blood enters the battlefield, if its mana cost was not paid, it becomes night.
Daybound",,3,3,"Shel, Moon Champion",Legendary Creature — Werewolf,,R,"Journey costs you pay to cast red or green creatures cost {1} less.
Nightbound",,4,3,Anna Podedworna,Julia Page,https://akreon.artstation.com/,https://www.pinterest.com/juliapage42/_created,
50,Vanguard's Primality,Vanguards Primality.png,,,{1}{G},Instant,"Cast this spell only during combat. All combat damage from creatures you don’t control is assigned to target creature you control, regardless of declared blockers.",The Bindareien charge ahead. They do not retreat.,,,,,,,,,,,Dmitry Burmak,,https://burmak.artstation.com/,,
51,"Akkeri, Giant-friend",Akkeri Giant-friend.png,,,{3}{R}{G}{G},Legendary Creature — Elephant,"Defender, trample
If another creature you control takes damage, Akkeri, Giant-friend can attack as though it did not have defender until end of turn.
{R}{G}: Creatures you control take 1 damage. Draw a card.",,6,10,,,,,,,,,Goro Fujita,,https://www.gorofujita.com/,,
52,Confounding Passenger,Confounding Passenger.png,,,{G}{U},Creature — Cat,"Whenever a player casts a spell, if no mana was spent to cast that spell, that player draws two cards.","Little Odin ate well, and so did the rest of the caravan.",1,4,,,,,,,,,Rebecca Guay,,http://www.rebeccaguay.com/,,
53,Jardhus Councilman,Jardhus Councilman.png,,,{2}{W}{U},Creature — Human Advisor,"Will of the council — When Jardhus Councilman enters the battlefield, starting with you, each player votes for a creature on the battlefield. Exile each creature with the most votes or tied for most votes. For as long as that card remains exiled, its owner may play it. A spell cast this way costs {2} more to cast and has cascade.",,2,2,,,,,,,,,Unknown,,,,
54,Remorhaz Egg,Remorhaz Egg.png,,Ropey Junior.png,{U}[R},Legendary Creature — Insect Egg,"Defender
At the beginning of your upkeep, put a frostfire counter on Remorhaz Egg.
Whenever you cast an instant or sorcery, put two frostfire counters on Remorhaz Egg.
Whenever you place a counter on Remorhaz Egg, if it has five or more frostfire counters, remove them and transform it.",,0,4,Ropey Junior,Legendary Creature — Insect,,UR,"Whenever a creature enters the battlefield from exile, return target instant or sorcery from your graveyard to your hand.
{R}: Ropey Junior gains +1/+0 until end of turn.",,5,4,Unknown,Ralph Horsley,,http://www.ralphhorsley.co.uk/,"Ralph Horsley's name is formatted as ""RalphHorsley"". I regret the error."
55,Seiðr-cursed Bairn,Seidr-cursed Bairn.png,,,{1}{W}{B},Creature — Human Warlock,"Lifelink
Sacrifice another creature: Seiðr-cursed Bairn gains +2/+2 until end of turn.","Ambiville tried to reach out to Siv’s heart, and she shunned him in fear.",2,2,,,,,,,,,toherrys,,https://www.deviantart.com/toherrys,,I listed an old username for toherrys as the art credit on this card. I regret the error.
56,"Sigurda, Jardhus's Finest",Sigurda Jardhuss Finest.png,,,{1}{G}{W},Legendary Creature — Human Soldier,"Vigilance
Whenever a creature you own enters exile, put a +1/+1 counter on Sigurda, Jardhus’s Finest.",Only her affection for Bjorn could coax her from the city she protected.,2,4,,,,,,,,,Anastasia Kustova,,https://reddress.artstation.com/,,
57,"Thorkell, Jomsviking",Thorkell Jomsviking.png,,,{2}{R}{W},Legendary Creature — Human Berserker,"Reveal this card from your hand, discard another card: Create a Treasure token. Activate only as a sorcery once per turn.
Sacrifice this creature during your end step if mana from a Treasure token was not spent to cast it.
Haste, double strike",,6,2,,,,,,,,,Sebijy,,https://www.deviantart.com/sebijy,,
58,Thorvaela's Axe,Thorvaelas Axe.png,,,{3}{B}{R},Legendary Artifact — Equipment,"Equipped creature gets +2/+0.
Sacrifice a creature: Equipped creature gets +3/-1 until end of turn.
Equip {0}. If Thorvaela’s Axe is attached to a creature, pay 4 life as an additional cost.",,,,,,,,,,,,Dima Goryainov,,https://chimodos.artstation.com/,,
59,"Vrækæ, Tyrant of Old",Vrækæ Tyrant of Old.png,,,{5}{U}{B},Legendary Creature — Behir,"Whenever a creature is returned to its owner’s hand, counter up to one triggered ability.
2U: Target creature that entered the battlefield this turn returns to its owner’s hand.
2B: Destroy target creature that entered the battlefield this turn.","“Quake in fear, mortals! This is my domain!”",6,6,,,,,,,,,Wizards of the Coast,,,,
60,Yrsa's Bargain,Yrsas Bargain.png,,,{1}{B}{G},Sorcery,"Exile a creature from a graveyard with power 5 or greater. Each opponent mills X, where X is the power of the exiled creature. Add X mana of any color to your mana pool.",Vrækæ’s body became Yrsa’s fuel.,,,,,,,,,,,MagicnaAnavi,,https://www.deviantart.com/magicnaanavi,,
61,Sleeping Frue,Sleeping Frue.png,,,{3}{U/B},Creature — Human Noble,"Ward {4}
Pay 1 life: Add one mana of any color. Spend this mana only to pay Journey costs.",Her dreams and nightmares consist only of her dear child returning.,1,3,,,,,,,,,Cornelis de Vos,,https://www.mutualart.com/Artist/Cornelis-de-Vos/465E332E311A8B3B/Artworks,,
62,Blood-soaked Cap,Blood-soaked Cap.png,,,{1},Artifact,{T}: You gain 1 life.,Bjorn took the cap off his head and swished it around the troll’s blood as Rune stared in equal parts curiosity and disgust.,,,,,,,,,,,mattforsyth,,https://mattforsyth.artstation.com/,,
63,Bracelet of Yrsa,Bracelet of Yrsa.png,,,{2},Artifact,"If Bracelet of Yrsa becomes tapped, sacrifice it.
{T}: Reveal your hand to target opponent, then draw a card.
{T}: Target opponent reveals their hand. Choose a nonland card with mana value 2 or less. That player discards that card. Activate only a sorcery.
{1}{U}{B}: Draw a card. Activate this ability only once per turn.",,,,,,,,,,,,AnthonyH318,,https://www.deviantart.com/anthonyh318,,
64,Political Map of Gardarík,Political Map of Gardarík.png,,,{3},Artifact,"{1}, {T}: The next spell you cast for its Journey cost costs {2} less until end of turn.
Sacrifice Political Map of Gardarík: Draw a card.",A necessary tool for navigating the continent in these times of conflict.,,,,,,,,,,,DeridiasDesigns,,https://www.deviantart.com/deridiasdesigns,,"Due to an oversight, I omitted the credit of the illustrator from the face of the card. I regret the error. "
65,"Rauthrn, Biting Glaive",Rauthrn Biting Glaive.png,,Rauthrn Dissolver of Steel.png,{3},Legendary Artifact — Equipment,"Equipped creature gets +2/+1 and has “When this creature attacks, destroy target Equipment attached to an opponent’s creature.”
Equip {1}",The blade of a dragonsmith has few that can rival it…,,,"Rauthrn, Dissolver of Steel",Legendary Artifact Creature — Dragon,{3},C,"Flying
When Rauthrn, Dissolver of Steel enters the battlefield, destroy all Equipment.",...because the breath of the dragon has left none.,3,3,Donald Gremillion,Allagar,https://www.donaldgremillion.com/,https://www.deviantart.com/allagar,
66,Yngvi's Carraige,Yngvis Carraige.png,,,{2},Artifact — Vehicle,"{T}, Tap a creature you control: Add three mana of any color. Spend this mana only to pay Journey costs.
Crew 1",,3,3,,,,,,,,,JMXD,,https://www.deviantart.com/jmxd,,
67,The Ashen Rose,The Ashen Rose.png,,,,Land,"{T}: Add {C}.
{T}, {1}, Sacrifice target artifact you control: Add mana of any color equal to the mana value of that artifact. ","A small smithy in the heart of Ravndalr is an unexpected place for a dark elf perfecting his craft, but it has welcomed him all the same.",,,,,,,,,,,ReneAigner,,https://reneaigner.artstation.com/,,
68,Black Market of Jardhus,Black Market of Jardhus.png,,,,Land,"{T}: Add {B}.
{2}{B}, {T}: Search your library for a card with a Journey value of 4 or higher, reveal it, put it into your hand, then shuffle. You lose 2 life.",Storolf turned a blind eye. The illicit holmium was abundant.,,,,,,,,,,,Rodimus25,,https://www.deviantart.com/rodimus25,,
69,Holmium Mines,Holmium Mines.png,,,,Land,"{T}: Add {C}.
{1}, {T}: Target attacking creature with an Equipment attached must be blocked this turn, if able.",The mines in Jardhus are renowned for the strange magnetic substance that can be found there. It is all meant to go to Skjöldr Scefing’s war efforts.,,,,,,,,,,,Henry Ledesma,,https://henryl.artstation.com/,,
1,Spirit,T1_Spirit.png,Y,,,Token Creature — Spirit,Flying,,1,1,,,,,,,,,Carlos Arellano,,https://www.deviantart.com/yaddar,,I listed Carlos on the card by his username. I regret the error.
2,Spirit,T2_Spirit.png,Y,,,Token Creature — Spirit,,,2,2,,,,,,,,,Max Kostin,,https://maxkostin.artstation.com/,,
3,Human Rogue,T3_Human Rogue.png,Y,,,Token Creature — Human Rogue,Deathtouch,,1,1,,,,,,,,,Link Chen,,https://blackspawn.artstation.com/,,
4,Human Shaman,T4_Human Shaman.png,Y,,,Token Creature — Human Shaman,,,1,1,,,,,,,,,Russell Dongjun Lu,,https://ludongjun.artstation.com/,,
5,Zombie Berserker,T5_Zombie Berserker.png,Y,,,Token Creature — Zombie Berserker,,,2,2,,,,,,,,,klamatu,,https://www.deviantart.com/klamatu,,
6,Treasure,T6_Treasure.png,Y,,,Token Artifact — Treasure,"{T}, Sacrifice this artifact: Add one mana of any color to your mana pool.",,,,,,,,,,,,Unknown,,,,
`;
export default data;
