// HACK: move data to a real csv file
export const data = `id,name,image_file,is_token?,backside_file
1,"Ambiville Ironstoad // Ambiville, Mystra's Kin",Ambiville Ironstoad.png,,Ambiville Mystra's Kin.png
2,Glimpse Ragnarök,Glimpse Ragnarök.png,,
3,Healing Verse,Healing Verse.png,,
4,Hug the Yeti,Hug the Yeti.png,,
5,Jarl's Guardsman,Jarls Guardsman.png,,
6,Judge the Meek,Judge the Meek.png,,
7,No Pets Allowed,No Pets Allowed.png,,
8,Priest of the Æsir,Priest of the Æsir.png,,
9,Seamstress Karl,Seamstress Karl.png,,
10,Tale of Heroics,Tale of Heroics.png,,
11,Blue Bard's Insight,Blue Bards Insight.png,,
12,Judge the Impotent,Judge the Impotent.png,,
13,Relinquish Control,Relinquish Control.png,,
14,Rune of Algiz,Rune of Algiz.png,,
15,"Rune, the Blue Bard",Rune the Blue Bard.png,,
16,Seal of the Old Tyrant,Seal of the Old Tyrant.png,,
17,Thoughtful Karl,Thoughtful Karl.png,,
18,Trouble in the Black Market,Trouble in the Black Market.png,,
19,Vrækæ's Desolation,Vrækæs Desolation.png,,
20,Chainer of Draugr,Chainer of Draugr.png,,
21,Commune After Sacrifice,Commune After Sacrifice.png,,
22,Draugr Berserker,Draugr Berserker.png,,
23,Draugr Captor,Draugr Captor.png,,
24,Fearful Karl,Fearful Karl.png,,
25,Incursion of Hardatr,Incursion of Hardatr.png,,
26,Kaldr Volundormr,Kaldr Volundormr.png,,
27,Malevolent Vandr,Malevolent Vandr.png,,
28,Phase Spider,Phase Spider.png,,
29,"Storolf, Jarl of Jardhus",Storolf Jarl of Jardhus.png,,
30,Vandr's Heartstone,Vandrs Heartstone.png,,
31,Yrsa's Manipulation,Yrsas Manipulation.png,,
32,Cave Kobold,Cave Kobold.png,,
33,Frenzying Redcap,Frenzying Redcap.png,,
34,Frostdweller Goblin,Frostdweller Goblin.png,,
35,God-King's Censure ,God-Kings Censure.png,,
36,Judge the Defiant,Judge the Defiant.png,,
37,Motivated Karl,Motivated Karl.png,,
38,Ransack the Estates,Ransack the Estates.png,,
39,Stone Worm,Stone Worm.png,,
40,"Throvaela, Vandr Killer // The Coven of Isstnar",Thorvaela Vandr Killer.png,,The Coven of Isstnar.png
41,"Will, Defiant Convict",Will Defiant Convict.png,,
42,Apothecary Volva,Apothecary Volva.png,,
43,Basilisk Wasp,Basilisk Wasp.png,,
44,Bjorn the Giant,Bjorn the Giant.png,,
45,"Bones, Ice-hearted",Bones Ice-hearted.png,,
46,Captive Innkeeper,Captive Innkeeper.png,,
47,Hunt for Game,Hunt for Game.png,,
48,Savage Karl,Savage Karl.png,,
49,"Shel, Pack's Blood // Shel, Moon Champion",Shel Packs Blood.png,,Shel Moon Champion.png
50,Vanguard's Primality,Vanguards Primality.png,,
51,"Akkeri, Giant-friend",Akkeri Giant-friend.png,,
52,Confounding Passenger,Confounding Passenger.png,,
53,Jardhus Councilman,Jardhus Councilman.png,,
54,Remorhaz Egg // Ropey Junior,Remorhaz Egg.png,,Ropey Junior.png
55,Seiðr-cursed Bairn,Seidr-cursed Bairn.png,,
56,"Sigurda, Jardhus's Finest",Sigurda Jardhuss Finest.png,,
57,"Thorkell, Jomsviking",Thorkell Jomsviking.png,,
58,Throvaela's Axe,Thorvaelas Axe.png,,
59,"Vrækæ, Tyrant of Old",Vrækæ Tyrant of Old.png,,
60,Yrsa's Bargain,Yrsas Bargain.png,,
61,Sleeping Frue,Sleeping Frue.png,,
62,Blood-soaked Cap,Blood-soaked Cap.png,,
63,Bracelet of Yrsa,Bracelet of Yrsa.png,,
64,Political Map of Gardarík,Political Map of Gardarík.png,,
65,"Rauthrn, Biting Glaive // Rauthrn, Dissolver of Steel",Rauthrn Biting Glaive.png,,Rauthrn Dissolver of Steel.png
66,Yngvi's Carraige,Yngvis Carriage.png,,
67,The Ashen Rose,The Ashen Rose.png,,
68,Black Market of Jardhus,Black Market of Jardhus.png,,
69,Holmium Mines,Holmium Mines.png,,
1,Spirit,T1_Spirit.png,Y,
2,Spirit,T2_Spirit.png,Y,
3,Human Rogue,T3_Human Rogue.png,Y,
4,Human Shaman,T4_Human Shaman.png,Y,
5,Zombie Berserker,T5_Zombie Berserker.png,Y,
6,Treasure,T6_Treasure.png,Y,
`;

export default data;
